avail_games = {
    "games": [
        "lit-lightbulb",
        "volume-container",
        "balance-scale-weigh",
        "blood-type",
        "plant-tree",
        "scale-weigh",
        "boil-water",
        "conductivity",
        "wash-clothes",
        "volume-stone",
        "cooking",
        "use-bandage",
        "forge-key",
        "bath-tub-water-temperature",
        "space-walk",
        "hang-painting",
        "clean-energy",
        "take-photo",
        "multimeter",
        "sunburn",
        "metal-detector",
        "volume",
        "make-campfire",
        "inclined-plane",
        "bird-life-cycle",
        "sweep-floor",
        "thermometer",
        "refrigerate-food",
        "balance-scale-heaviest",
        "make-ice-cubes",
        "mix-paint",
    ],
    "example": "dishwasher",
}


games_without_randomness = [
    "lit-lightbulb",
    "plant-tree",
    "boil-water",
    "space-walk",
    "sunburn",
    "make-campfire",
    "bird-life-cycle",
    "make-ice-cubes",
    "forge-key",
]


game_difficulty_level = {
    "easy": [
        "blood-type",
        "thermometer",
        "mix-paint",
        "lit-lightbulb",
        "scale-weigh",
        "use-bandage",
        "clean-energy",
        "multimeter",
        "hang-painting",
        "volume",
        "bath-tub-water-temperature",
        "sunburn",
        "space-walk",
        "take-photo",
        "volume-container",
    ],
    "medium": [
        "conductivity",
        "make-campfire",
        "sweep-floor",
        "refrigerate-food",
        "volume-stone",
        "bird-life-cycle",
        "balance-scale-heaviest",
        "make-ice-cubes",
    ],
    "difficult": [
        "plant-tree",
        "boil-water",
        "cooking",
        "forge-key",
        "balance-scale-weigh",
        "metal-detector",
        "inclined-plane",
        "wash-clothes",
    ],
}

sorted_game_list = [
    "mix-paint",
    "blood-type",
    "thermometer",
    "clean-energy",
    "lit-lightbulb",
    "scale-weigh",
    "use-bandage",
    "hang-painting",
    "multimeter",
    "volume",
    "sunburn",
    "space-walk",
    "sweep-floor",
    "volume-container",
    "bath-tub-water-temperature",
    "conductivity",
    "make-campfire",
    "refrigerate-food",
    "volume-stone",
    "bird-life-cycle",
    "balance-scale-weigh",
    "metal-detector",
    "cooking",
    "make-ice-cubes",
    "balance-scale-heaviest",
    "take-photo",
    "plant-tree",
    "boil-water",
    "forge-key",
    "inclined-plane",
    "wash-clothes",
]

sorted_game_list_for_plot = [
    "paint",
    "blood",
    "thermo",
    "energy",
    "bulb",
    "scale",
    "bandage",
    "hang",
    "multi",
    "volume",
    "sunburn",
    "space",
    "sweep",
    "container",
    "bathtub",
    "conduct",
    "campfire",
    "fridge",
    "stone",
    "bird",
    "weigh",
    "metal",
    "cooking",
    "ice",
    "heavy",
    "photo",
    "plant",
    "boil",
    "key",
    "plane",
    "washing",
]


sorted_game_list_for_decision = [
    "mix-paint",
    "blood-type",
    "thermometer",
    "clean-energy",
    "lit-lightbulb",
    # "scale-weigh",
    "use-bandage",
    "hang-painting",
    # "multimeter",
    # "volume",
    "sunburn",
    "space-walk",
    "sweep-floor",
    "volume-container",
    "bath-tub-water-temperature",
    # "conductivity",
    "make-campfire",
    "refrigerate-food",
    # "volume-stone",
    "bird-life-cycle",
    # "balance-scale-weigh",
    # "metal-detector",
    "cooking",
    "make-ice-cubes",
    # "balance-scale-heaviest",
    "take-photo",
    "plant-tree",
    "boil-water",
    "forge-key",
    "inclined-plane",
    "wash-clothes",
]
